<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <!-- 下面这个配置可以关闭packages中因安装ScottPlot.WinForms而出现可能不兼容的警告 -->
    <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>

  <!-- 关键：框架引用，不是NuGet PackageReference！不要去nuget搜这个包安装 -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.29" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.29" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.1.4" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="6.1.4" />
    <PackageReference Include="S7netplus" Version="0.20.0" />
    <PackageReference Include="ScottPlot" Version="5.1.59" />
    <PackageReference Include="ScottPlot.WinForms" Version="5.1.59" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyS7NetPlus.Common\MyS7NetPlus.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tags.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- appsettings.json 配置文件，自动复制到输出目录 -->
  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Database\" />
  </ItemGroup>

</Project>